env_id = "ALE/Pacman-v5"
policy = "CnnPolicy"
algorithm = "PPO"
learning_rate = 5e-4  
gamma = 0.99
gae_lambda=  0.95
n_steps = 128
ent_coef = 0.01 
vf_coef = 0.5
clip_range = 0.2
clip_range_vf = 1
n_epochs = 6
batch_size = 128 
max_grad_norm = 0.4
total_timesteps = 2000000
model_name = "PPO_Pacman"
export_path = "./exports/"
videos_path = "./videos/"